package com.es.sys.pojo;

import java.util.Date;

public class Attendens {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attendens.attendentsid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer attendentsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attendens.createdtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Date createdtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attendens.Endtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attendens.am_vaild
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer amVaild;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attendens.pm_vaild
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer pmVaild;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attendens.attendentsid
	 * @return  the value of Attendens.attendentsid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getAttendentsid() {
		return attendentsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attendens.attendentsid
	 * @param attendentsid  the value for Attendens.attendentsid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setAttendentsid(Integer attendentsid) {
		this.attendentsid = attendentsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attendens.createdtime
	 * @return  the value of Attendens.createdtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Date getCreatedtime() {
		return createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attendens.createdtime
	 * @param createdtime  the value for Attendens.createdtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attendens.Endtime
	 * @return  the value of Attendens.Endtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attendens.Endtime
	 * @param endtime  the value for Attendens.Endtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attendens.am_vaild
	 * @return  the value of Attendens.am_vaild
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getAmVaild() {
		return amVaild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attendens.am_vaild
	 * @param amVaild  the value for Attendens.am_vaild
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setAmVaild(Integer amVaild) {
		this.amVaild = amVaild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attendens.pm_vaild
	 * @return  the value of Attendens.pm_vaild
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getPmVaild() {
		return pmVaild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attendens.pm_vaild
	 * @param pmVaild  the value for Attendens.pm_vaild
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setPmVaild(Integer pmVaild) {
		this.pmVaild = pmVaild;
	}
}