package com.es.sys.pojo;

public class Daminandholiday {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Daminandholiday.id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Daminandholiday.Userid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Daminandholiday.Holidayid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer holidayid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Daminandholiday.Attendentsid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer attendentsid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Daminandholiday.id
	 * @return  the value of Daminandholiday.id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Daminandholiday.id
	 * @param id  the value for Daminandholiday.id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Daminandholiday.Userid
	 * @return  the value of Daminandholiday.Userid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Daminandholiday.Userid
	 * @param userid  the value for Daminandholiday.Userid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Daminandholiday.Holidayid
	 * @return  the value of Daminandholiday.Holidayid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getHolidayid() {
		return holidayid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Daminandholiday.Holidayid
	 * @param holidayid  the value for Daminandholiday.Holidayid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setHolidayid(Integer holidayid) {
		this.holidayid = holidayid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Daminandholiday.Attendentsid
	 * @return  the value of Daminandholiday.Attendentsid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getAttendentsid() {
		return attendentsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Daminandholiday.Attendentsid
	 * @param attendentsid  the value for Daminandholiday.Attendentsid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setAttendentsid(Integer attendentsid) {
		this.attendentsid = attendentsid;
	}
}