package com.es.sys.pojo;

public class Employees {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Employees.id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Employees.department_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Employees.user_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Employees.id
	 * @return  the value of Employees.id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Employees.id
	 * @param id  the value for Employees.id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Employees.department_id
	 * @return  the value of Employees.department_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Employees.department_id
	 * @param departmentId  the value for Employees.department_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Employees.user_id
	 * @return  the value of Employees.user_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Employees.user_id
	 * @param userId  the value for Employees.user_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}