package com.es.sys.pojo;

import java.util.Date;

public class Holiday {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.holiday_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer holidayId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.days
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Integer days;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.start_time
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.end_time
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.alid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private String alid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.audit_gnature
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private String auditGnature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.createdtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Date createdtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.reason
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Holiday.modifiedTime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	private Date modifiedtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.holiday_id
	 * @return  the value of Holiday.holiday_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getHolidayId() {
		return holidayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.holiday_id
	 * @param holidayId  the value for Holiday.holiday_id
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setHolidayId(Integer holidayId) {
		this.holidayId = holidayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.days
	 * @return  the value of Holiday.days
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Integer getDays() {
		return days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.days
	 * @param days  the value for Holiday.days
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setDays(Integer days) {
		this.days = days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.start_time
	 * @return  the value of Holiday.start_time
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.start_time
	 * @param startTime  the value for Holiday.start_time
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.end_time
	 * @return  the value of Holiday.end_time
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.end_time
	 * @param endTime  the value for Holiday.end_time
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.alid
	 * @return  the value of Holiday.alid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public String getAlid() {
		return alid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.alid
	 * @param alid  the value for Holiday.alid
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setAlid(String alid) {
		this.alid = alid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.audit_gnature
	 * @return  the value of Holiday.audit_gnature
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public String getAuditGnature() {
		return auditGnature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.audit_gnature
	 * @param auditGnature  the value for Holiday.audit_gnature
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setAuditGnature(String auditGnature) {
		this.auditGnature = auditGnature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.createdtime
	 * @return  the value of Holiday.createdtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Date getCreatedtime() {
		return createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.createdtime
	 * @param createdtime  the value for Holiday.createdtime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.reason
	 * @return  the value of Holiday.reason
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.reason
	 * @param reason  the value for Holiday.reason
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Holiday.modifiedTime
	 * @return  the value of Holiday.modifiedTime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public Date getModifiedtime() {
		return modifiedtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Holiday.modifiedTime
	 * @param modifiedtime  the value for Holiday.modifiedTime
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	public void setModifiedtime(Date modifiedtime) {
		this.modifiedtime = modifiedtime;
	}
}