package com.es.sys.mapper ;

import com.es.sys.pojo.Attendens;
import com.es.sys.pojo.AttendensExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendensMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int countByExample(AttendensExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int deleteByExample(AttendensExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int deleteByPrimaryKey(Integer attendentsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int insert(Attendens record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int insertSelective(Attendens record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */List<Attendens> selectByExample(AttendensExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	Attendens selectByPrimaryKey(Integer attendentsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */int updateByExampleSelective(@Param("record") Attendens record,@Param("example") AttendensExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */int updateByExample(@Param("record") Attendens record,@Param("example") AttendensExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int updateByPrimaryKeySelective(Attendens record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Attendens
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int updateByPrimaryKey(Attendens record);
}