package com.es.sys.mapper ;

import com.es.sys.pojo.Daminandholiday;
import com.es.sys.pojo.DaminandholidayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DaminandholidayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int countByExample(DaminandholidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int deleteByExample(DaminandholidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int insert(Daminandholiday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int insertSelective(Daminandholiday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */List<Daminandholiday> selectByExample(DaminandholidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	Daminandholiday selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */int updateByExampleSelective(@Param("record") Daminandholiday record,@Param("example") DaminandholidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */int updateByExample(@Param("record") Daminandholiday record,@Param("example") DaminandholidayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int updateByPrimaryKeySelective(Daminandholiday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Daminandholiday
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int updateByPrimaryKey(Daminandholiday record);
}