package com.es.sys.mapper ;

import com.es.sys.pojo.Admin;
import com.es.sys.pojo.Employees;
import com.es.sys.pojo.EmployeesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int countByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int deleteByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int insert(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int insertSelective(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */List<Employees> selectByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	Employees selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */int updateByExampleSelective(@Param("record") Employees record,@Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */int updateByExample(@Param("record") Employees record,@Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int updateByPrimaryKeySelective(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Employees
	 * @mbggenerated  Sat Mar 02 11:06:11 CST 2019
	 */
	int updateByPrimaryKey(Employees record);

	Admin selectFind();
}